config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'users#index'
  apipie
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  resources :users, only: %i[index edit update destroy]
  resources :transactions, only: %i[create show]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
# frozen_string_literal: true

class Transaction < ApplicationRecord
  belongs_to :user
  after_create :set_transaction_uuid
  after_create :set_user_transactions_sum
  validates :amount, presence: true, numericality: true

  default_scope { order('created_at DESC') }

  def self.delete_older_than(minutes)
    Transaction.all.each { |t| ((Time.now - t.created_at) / 60) > minutes ? t.destroy : nil }
  end

  private

  def set_transaction_uuid
    update!(uuid: SecureRandom.uuid)
  end

  def set_user_transactions_sum
    user_t_sum = user[:total_transaction_sum]
    total_sum = user_t_sum + amount
    user.update!(total_transaction_sum: total_sum)
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  require 'csv'
  scope :active, -> { where status: 'active' }
  has_many :transactions, dependent: :destroy
  validates :name, presence: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }

  def active?
    status == 'active'
  end

  def self.import_new_users(_file)
    get_users_rows(_file) do |row|
      user = User.find_by(name: row['name'], email: row['email'])
      User.create(row) if user.nil?
    end
  end

  def self.get_users_rows(file)
    CSV.foreach(File.path(file), headers: true) do |row|
      yield row.to_hash
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
end

app/controllers/transactions_controller.rb
# frozen_string_literal: true

class TransactionsController < ApplicationController
  include TransactionsDoc

  def create
    xml_params = xml_params_hash
    t_params = if xml_params.any?
                 transaction_params.merge!(xml_params)
               else
                 transaction_params
               end
    user = User.find(t_params[:user_id])
    if user&.active?
      transaction = user.transactions.create(t_params.except(:user_id))
      if transaction.valid? && t_params[:amount] != '0'
        render json: { status: 200, message: { transaction: transaction.as_json(except: %i[created_at updated_at]) } }
      else
        transaction.update(amount: 0, status: 'error')
        render json: { status: 422, message: { transaction: transaction.as_json(except: %i[created_at updated_at]) } }, status: 422
      end
    else
      render_not_found_json
    end
  rescue StandardError
    render_not_found_json
  end

  def show
    user = User.find(t_params[:id])
    @user_transactions = user.transactions
  end
end

private

def t_params
  params.permit(:id)
end

def transaction_params
  params.permit(:user_id, :amount)
end

def render_not_found_json
  render json: { status: 404, message: "No such user found or it's inactive" }, status: 404
end

def xml_params_hash
  xml_string = request.body.read
  begin
    helpers.xml_to_hash(xml_string)
  rescue StandardError
    {}
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @users = User.all.order('id')
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to action: :index
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to action: :index
  end

  private

  def user_params
    user_params = params.require(:user).permit(:status, :name, :description, :email)
    user_params.merge(params.permit(:status))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/transactions_helper.rb
# frozen_string_literal: true

module TransactionsHelper
  NUMBER_REGEX = /\A[-+]?[0-9]*\.?[0-9]+\Z/.freeze

  def xml_to_hash(xml_string)
    hash = Hash.from_xml(xml_string)
    transaction_h = hash['transaction']
    transaction_h.each do |k, v|
      transaction_h[k] = v.to_d if k == 'amount' && v.match(NUMBER_REGEX)
    end
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PaymentSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/transactions/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <table class="table">
        <thead>
          <tr>
            <th>Amount</th>
            <th>Status</th>
            <th>Uuid</th>
            <th><%= link_to 'Back', users_path %></th>
          </tr>
        </thead>
        <tbody>
          <% @user_transactions.each do |transaction| %>
            <tr>
              <td><%=transaction[:amount]%></td>
              <td><%=transaction[:status]%></td>
              <td><%=transaction[:uuid]%></td>
              <td></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container" style="margin-top:34px">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="form-group">
        <%= form_for @user do |f| %>
          <%= f.label 'Name', class:'control-label' %><br>
          <%= f.text_field :name, class:'form-control' %><br>

          <%= f.label 'Description', class:'control-label' %><br>
          <%= f.text_area :description,class:'form-control' %><br>

          <%= f.label 'Email', class:'control-labe' %><br>
          <%= f.text_field :email, class:'form-control' %><br>

          <%= f.label 'Status', class:'control-labe' %><br>
          <%= select_tag "status", raw('<option>active</option><option>inactive</option>'), method: :patch, class:'form-control'%>
          <div style="margin-top:20px;">
            <%= f.submit "Submit changes", class:'btn btn-default' %>
            <%= link_to 'Cancel', users_path, class:'btn btn-default' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="main_container">
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <table class="table">
          <thead>
            <tr>
              <th>ID</th>
              <th>Name</th>
              <th>Description</th>
              <th>Email</th>
              <th>Status</th>
              <th>Transactions sum</th>
              <th>Transactions</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= user[:id] %></td>
                <td><%= user[:name] %></td>
                <td><%= user[:description] %></td>
                <td><%= user[:email] %></td>
                <td><%= user[:status] %></td>
                <td><%= user[:total_transaction_sum] %></td>
                <td><%= link_to 'View', transaction_path(user.id) %></td>
                <td><%= link_to 'Edit', edit_user_path(user.id) %> / <%= link_to 'Delete', user_path(user), method: :delete %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>